name = "kubby-buddy-website"
   type = "webpack"
   compatibility_date = "2023-07-01"
   account_id = "3f0b69666ae9df921de25c9b425afe7e"
   workers_dev = true
   main = "src/worker.ts"
   route = "https://kubbybuddy.com"

   [site]
   bucket = "./public"
